version: '3.8'
services:
  web:
    image: nginx
    volumes:
      - ./web/index.html:/usr/share/nginx/html/index.html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - app

  app:
    build: ./app
    ports:
      - "3000:3000"
